# Generated by Django 6.0.5 on 2026-05-26 19:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user", models.CharField(blank=True, default="", max_length=150)),
                ("endpoint", models.CharField(max_length=128)),
                ("method", models.CharField(max_length=8)),
                ("payload_diff", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name_plural": "Audit entries",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("value", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ticker", models.CharField(db_index=True, max_length=32)),
                ("group", models.CharField(max_length=64)),
                (
                    "action",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=4
                    ),
                ),
                ("amount_eur", models.DecimalField(decimal_places=4, max_digits=14)),
                ("price_local", models.DecimalField(decimal_places=6, max_digits=14)),
                ("listing_currency", models.CharField(max_length=8)),
                ("eur_per_local", models.DecimalField(decimal_places=8, max_digits=12)),
                ("shares", models.DecimalField(decimal_places=8, max_digits=18)),
                (
                    "fee_eur",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_class",
                    models.CharField(
                        choices=[("stocks", "Stocks"), ("etfs", "ETFs")], max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "target_weight",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["asset_class", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asset_class", "name"),
                        name="unique_group_per_asset_class",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("portfolio", "Portfolio"),
                            ("watchlist", "Watchlist"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "asset_class",
                    models.CharField(
                        choices=[("stocks", "Stocks"), ("etfs", "ETFs")], max_length=10
                    ),
                ),
                ("group", models.CharField(max_length=64)),
                ("ticker", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=128)),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["kind", "group", "ticker"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "ticker"), name="unique_ticker_per_kind"
                    )
                ],
            },
        ),
    ]
