# Generated by Django 6.0.5 on 2026-05-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupconfig",
            name="asset_class",
            field=models.CharField(
                choices=[("stocks", "Stocks"), ("etfs", "ETFs"), ("crypto", "Crypto")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="holding",
            name="asset_class",
            field=models.CharField(
                choices=[("stocks", "Stocks"), ("etfs", "ETFs"), ("crypto", "Crypto")],
                max_length=10,
            ),
        ),
    ]
