# Generated by Django 6.0.5 on 2026-05-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0002_add_crypto_asset_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="swap_group_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
