/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Cheap probe used by the SPA on boot to decide whether to show the
         *     login page or the app. Never errors.
         */
        get: operations["portfolio_app_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login View
         * @description Authenticate against Django's user model + start a session. POST is
         *     deliberately open (``auth=None``) so the user can log in without already
         *     having a session; CSRF for login is left to same-origin SOP for the SPA.
         */
        post: operations["portfolio_app_api_login_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout View
         * @description End the current session. Requires being logged in (uses the default
         *     ``django_auth``) and thus enforces CSRF on the POST.
         */
        post: operations["portfolio_app_api_logout_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description Current positions for ``asset_class`` valued in EUR, plus group breakdown.
         */
        get: operations["portfolio_app_api_get_portfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description EUR value time-series for ``asset_class`` (by ticker, by group, total, invested).
         */
        get: operations["portfolio_app_api_get_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard
         * @description Cross-sleeve KPIs + 90-day sparkline + top movers + adapter status.
         */
        get: operations["portfolio_app_api_get_dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diversification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Diversification
         * @description Pairwise return correlation matrix + diversification summary stats.
         */
        get: operations["portfolio_app_api_get_diversification"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio Signals
         * @description BUY / HOLD / TRIM scores for every portfolio holding in ``asset_class``.
         *
         *     Same scoring engine as the watchlist (sub-signals: trend, momentum, MACD,
         *     mean-reversion → composite ∈ [-1, +1] → BUY/HOLD/TRIM), but scoped to names
         *     the user already owns. Powers the signal-map scatter on Portfolio › Stocks
         *     so the user can see at a glance which positions are stretched (TRIM
         *     candidates) vs. oversold (BUY-more candidates) before their next monthly
         *     deposit. Cached 10 min keyed by (adapter, asset_class, tx revision).
         */
        get: operations["portfolio_app_api_get_portfolio_signals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Watchlist Signals
         * @description BUY / WATCH / AVOID scores for every name on the watchlist.
         */
        get: operations["portfolio_app_api_get_watchlist_signals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["portfolio_app_api_list_transactions"];
        put?: never;
        /**
         * Create Transaction
         * @description Log a buy or sell. The backend estimates ``shares``, ``price_local``
         *     and ``eur_per_local`` from EOD market data on ``date`` (so the SPA only
         *     needs to send the EUR amount and date).
         */
        post: operations["portfolio_app_api_create_transaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Transactions
         * @description Stream the ledger as a CSV download.
         */
        get: operations["portfolio_app_api_export_transactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{tx_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Transaction */
        delete: operations["portfolio_app_api_delete_transaction"];
        options?: never;
        head?: never;
        /**
         * Update Transaction
         * @description Edit just the ``note`` and/or ``fee_eur`` on an existing transaction.
         *     Other fields (date/ticker/amount/shares/price/FX) are immutable -- delete
         *     and re-create if you need to change them.
         */
        patch: operations["portfolio_app_api_update_transaction"];
        trace?: never;
    };
    "/api/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Holding
         * @description Add a new portfolio or watchlist holding. Atomically logs the initial
         *     Transaction too if ``initial_amount_eur`` is given (portfolio only) -- the
         *     Holding is rolled back if the price fetch fails.
         */
        post: operations["portfolio_app_api_create_holding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holdings/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Holding
         * @description Remove a holding. Refuses if portfolio holding has any transactions
         *     (delete transactions first); watchlist holdings can be removed freely.
         */
        delete: operations["portfolio_app_api_delete_holding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Groups
         * @description List GroupConfig rows. Optional ``asset_class`` filter
         *     (``stocks`` or ``etfs``). Each row carries ``holdings_count`` so the
         *     Manage-Groups modal can show usage and gate destructive actions.
         */
        get: operations["portfolio_app_api_list_groups"];
        put?: never;
        /**
         * Upsert Group
         * @description Create or update a (asset_class, group_name) config (description +
         *     optional target weight). Idempotent.
         */
        post: operations["portfolio_app_api_upsert_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{asset_class}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Group
         * @description Remove a group. Refuses if any Holding still references it -- move/delete
         *     those first. Also refuses to delete the canonical 'ETFs' group while ETF
         *     holdings exist; ETF holdings have nowhere else to live.
         */
        delete: operations["portfolio_app_api_delete_group"];
        options?: never;
        head?: never;
        /**
         * Update Group
         * @description Update description / target_weight on an existing group.
         *
         *     Pass ``clear_target_weight=true`` to wipe the target back to NULL (e.g. a
         *     sleeve you no longer want to rebalance against).
         */
        patch: operations["portfolio_app_api_update_group"];
        trace?: never;
    };
    "/api/instruments/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Instruments
         * @description Resolve a company name or partial ticker through the active adapter's
         *     symbol-search endpoint (yfinance ``Search`` or Alpha Vantage ``SYMBOL_SEARCH``).
         *
         *     The optional ``type`` parameter filters hits to a single asset class --
         *     ``stocks`` (equity + mutual funds) or ``etfs`` -- so the Add-Stock modal can
         *     show only ETFs when adding to the ETFs sleeve and the global nav bar can
         *     skip non-stock noise.
         */
        get: operations["portfolio_app_api_search_instruments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{ticker}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Instrument Quote
         * @description Latest quote (price, change %, volume, last trading day).
         */
        get: operations["portfolio_app_api_get_instrument_quote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{ticker}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Instrument History
         * @description OHLCV history. ``interval`` in {daily, weekly, monthly}; ``range`` slices
         *     the trailing window (``1mo|3mo|6mo|1y|2y|5y|max``).
         */
        get: operations["portfolio_app_api_get_instrument_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{ticker}/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Instrument Indicators
         * @description Full technical indicator panel (price + SMA/EMA + RSI + MACD + Bollinger + z-score).
         */
        get: operations["portfolio_app_api_get_instrument_indicators"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{ticker}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Instrument Score
         * @description Composite BUY/HOLD/TRIM quant score for a single ticker.
         */
        get: operations["portfolio_app_api_get_instrument_score"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{ticker}/estimate-shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estimate Shares
         * @description Preview shares + USD/EUR FX for a hypothetical buy on a given date.
         *
         *     Powers the live preview in the Add-Investment modal (Phase 5).
         */
        get: operations["portfolio_app_api_estimate_shares"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["portfolio_app_api_get_settings"];
        /**
         * Update Settings
         * @description Persist a new AV API key and/or hot-swap the active adapter.
         */
        put: operations["portfolio_app_api_update_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cache/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear Cache
         * @description Wipe Django's view cache and the adapter's in-memory price cache.
         *
         *     Backs the top-bar "Refresh prices" button: the SPA POSTs here, gets back
         *     the adapter name + ISO timestamp, then bumps its ``pricesRevision`` store
         *     so every mounted view refetches. Returning a body (rather than 204) lets
         *     the SPA render an "Updated 14:32" badge after a successful refresh.
         */
        post: operations["portfolio_app_api_clear_cache"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** MeOut */
        MeOut: {
            /** Authenticated */
            authenticated: boolean;
            /** Username */
            username?: string | null;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Detail */
            detail: string;
            /** Limited */
            limited?: boolean | null;
        };
        /** LoginIn */
        LoginIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** GroupSummary */
        GroupSummary: {
            /** Group */
            group: string;
            /** Value Eur */
            value_eur: number;
            /** Cost Eur */
            cost_eur: number;
            /** Pnl Eur */
            pnl_eur: number;
            /** Return Pct */
            return_pct?: number | null;
            /** Weight */
            weight?: number | null;
            /** Target Weight */
            target_weight?: number | null;
            /** Drift Pct */
            drift_pct?: number | null;
        };
        /** PortfolioPosition */
        PortfolioPosition: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Group */
            group: string;
            /** Currency */
            currency: string;
            /** Shares */
            shares: number;
            /** Invested Eur */
            invested_eur: number;
            /**
             * Fees Eur
             * @default 0
             */
            fees_eur: number;
            /** Price Local */
            price_local?: number | null;
            /** Price Eur */
            price_eur?: number | null;
            /** Value Eur */
            value_eur?: number | null;
            /** Cost Eur */
            cost_eur: number;
            /** Pnl Eur */
            pnl_eur?: number | null;
            /** Return Pct */
            return_pct?: number | null;
            /** Weight */
            weight?: number | null;
        };
        /** PortfolioSnapshotOut */
        PortfolioSnapshotOut: {
            /** Asset Class */
            asset_class: string;
            /** Positions */
            positions: components["schemas"]["PortfolioPosition"][];
            /** By Group */
            by_group: components["schemas"]["GroupSummary"][];
            totals: components["schemas"]["PortfolioTotals"];
            /** Fx Rates */
            fx_rates: {
                [key: string]: number;
            };
        };
        /** PortfolioTotals */
        PortfolioTotals: {
            /** Value Eur */
            value_eur: number;
            /** Cost Eur */
            cost_eur: number;
            /** Pnl Eur */
            pnl_eur: number;
            /** Return Pct */
            return_pct?: number | null;
        };
        /** ValueHistoryOut */
        ValueHistoryOut: {
            /** Asset Class */
            asset_class: string;
            /** Dates */
            dates: string[];
            /** By Ticker */
            by_ticker: {
                [key: string]: (number | null)[];
            };
            /** By Group */
            by_group: {
                [key: string]: (number | null)[];
            };
            /** Total */
            total: (number | null)[];
            /** Invested */
            invested: (number | null)[];
        };
        /** AdapterStatus */
        AdapterStatus: {
            /** Name */
            name: string;
            /** Av Quota */
            av_quota: {
                [key: string]: unknown;
            };
        };
        /** DashboardOut */
        DashboardOut: {
            stocks: components["schemas"]["PortfolioTotals"];
            etfs: components["schemas"]["PortfolioTotals"];
            combined: components["schemas"]["PortfolioTotals"];
            sparkline: components["schemas"]["Sparkline"];
            /** Top Movers */
            top_movers: components["schemas"]["TopMover"][];
            adapter: components["schemas"]["AdapterStatus"];
        };
        /** Sparkline */
        Sparkline: {
            /** Dates */
            dates: string[];
            /** Values */
            values: (number | null)[];
        };
        /** TopMover */
        TopMover: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Asset Class */
            asset_class: string;
            /** Change Pct */
            change_pct: number;
            /** Last Close */
            last_close: number;
            /** Value Eur */
            value_eur?: number | null;
        };
        /** DiversificationOut */
        DiversificationOut: {
            /** Metric */
            metric: string;
            /** Asset Class */
            asset_class: string;
            /** Lookback Days */
            lookback_days: number;
            /** Tickers */
            tickers: string[];
            /** Matrix */
            matrix: (number | null)[][];
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Cached */
            cached: boolean;
        };
        /** PortfolioSignalsOut */
        PortfolioSignalsOut: {
            /** Cached */
            cached: boolean;
            /** Asset Class */
            asset_class: string;
            /** Items */
            items: components["schemas"]["WatchlistScoreOut"][];
        };
        /** WatchlistScoreOut */
        WatchlistScoreOut: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Group */
            group: string;
            /** Currency */
            currency: string;
            /** Status */
            status: string;
            /** Recommendation */
            recommendation: string;
            /** Last Price */
            last_price?: number | null;
            /** Roc 20D Pct */
            roc_20d_pct?: number | null;
            /** Rsi 14 */
            rsi_14?: number | null;
            /** Zscore 20 */
            zscore_20?: number | null;
            /** Trend */
            trend?: number | null;
            /** Momentum */
            momentum?: number | null;
            /** Macd */
            macd?: number | null;
            /** Mean Reversion */
            mean_reversion?: number | null;
            /** Score */
            score?: number | null;
            /** Signal */
            signal?: string | null;
        };
        /** WatchlistOut */
        WatchlistOut: {
            /** Cached */
            cached: boolean;
            /** Items */
            items: components["schemas"]["WatchlistScoreOut"][];
        };
        /** TransactionOut */
        TransactionOut: {
            /** Id */
            id: number;
            /** Date */
            date: string;
            /** Ticker */
            ticker: string;
            /** Group */
            group: string;
            /** Action */
            action: string;
            /** Amount Eur */
            amount_eur: number;
            /** Price Local */
            price_local: number;
            /** Listing Currency */
            listing_currency: string;
            /** Eur Per Local */
            eur_per_local: number;
            /** Shares */
            shares: number;
            /** Fee Eur */
            fee_eur: number;
            /** Note */
            note: string;
        };
        /**
         * TransactionCreate
         * @description Body for ``POST /api/transactions``. Backend estimates ``shares``,
         *     ``price_local`` and ``eur_per_local`` from EOD data on ``date``.
         */
        TransactionCreate: {
            /** Date */
            date: string;
            /** Ticker */
            ticker: string;
            /**
             * Action
             * @default buy
             */
            action: string;
            /** Amount Eur */
            amount_eur: number;
            /**
             * Listing Currency
             * @default USD
             */
            listing_currency: string;
            /**
             * Fee Eur
             * @default 0
             */
            fee_eur: number;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * TransactionPatch
         * @description Body for ``PATCH /api/transactions/{id}``. Only mutable fields.
         */
        TransactionPatch: {
            /** Note */
            note?: string | null;
            /** Fee Eur */
            fee_eur?: number | null;
        };
        /** HoldingOut */
        HoldingOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Asset Class */
            asset_class: string;
            /** Group */
            group: string;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            transaction?: components["schemas"]["TransactionOut"] | null;
        };
        /**
         * HoldingCreate
         * @description Body for ``POST /api/holdings``.
         *
         *     Creates a Holding row. If ``initial_amount_eur`` is provided (and
         *     ``kind='portfolio'``), atomically logs the first Transaction too -- the
         *     Holding is rolled back if the price fetch fails.
         *
         *     If ``group`` doesn't exist yet, a ``GroupConfig`` is auto-created with the
         *     optional ``target_weight`` / ``group_description``.
         */
        HoldingCreate: {
            /** Kind */
            kind: string;
            /** Asset Class */
            asset_class: string;
            /** Group */
            group: string;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Target Weight */
            target_weight?: number | null;
            /** Group Description */
            group_description?: string | null;
            /** Initial Amount Eur */
            initial_amount_eur?: number | null;
            /** Initial Date */
            initial_date?: string | null;
            /** Initial Fee Eur */
            initial_fee_eur?: number | null;
            /** Initial Note */
            initial_note?: string | null;
        };
        /** GroupOut */
        GroupOut: {
            /** Asset Class */
            asset_class: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Target Weight */
            target_weight?: number | null;
            /**
             * Holdings Count
             * @default 0
             */
            holdings_count: number;
        };
        /**
         * GroupCreate
         * @description Body for ``POST /api/groups``. Idempotent: get-or-create + update if exists.
         */
        GroupCreate: {
            /** Asset Class */
            asset_class: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Target Weight */
            target_weight?: number | null;
        };
        /**
         * GroupPatch
         * @description Body for ``PATCH /api/groups/{name}``. Both fields optional; ``None``
         *     leaves the existing value alone, an empty string / null target_weight
         *     clears it.
         */
        GroupPatch: {
            /** Description */
            description?: string | null;
            /** Target Weight */
            target_weight?: number | null;
            /**
             * Clear Target Weight
             * @default false
             */
            clear_target_weight: boolean;
        };
        /** InstrumentSearchHit */
        InstrumentSearchHit: {
            /** Symbol */
            symbol: string;
            /** Name */
            name?: string | null;
            /** Type */
            type?: string | null;
            /** Region */
            region?: string | null;
            /** Currency */
            currency?: string | null;
        };
        /** InstrumentQuoteOut */
        InstrumentQuoteOut: {
            /** Symbol */
            symbol: string;
            /** Price */
            price?: number | null;
            /** Open */
            open?: number | null;
            /** High */
            high?: number | null;
            /** Low */
            low?: number | null;
            /** Previous Close */
            previous_close?: number | null;
            /** Change */
            change?: number | null;
            /** Change Percent */
            change_percent?: number | null;
            /** Volume */
            volume?: number | null;
            /** Latest Trading Day */
            latest_trading_day?: string | null;
        };
        /**
         * HistoryFrameOut
         * @description OHLCV history, columns as parallel arrays (one entry per date).
         */
        HistoryFrameOut: {
            /** Symbol */
            symbol: string;
            /** Interval */
            interval: string;
            /** Dates */
            dates: string[];
            /** Open */
            open: (number | null)[];
            /** High */
            high: (number | null)[];
            /** Low */
            low: (number | null)[];
            /** Close */
            close: (number | null)[];
            /** Volume */
            volume: (number | null)[];
        };
        /**
         * IndicatorsOut
         * @description ``metrics.add_indicators`` output, returned split-orient.
         */
        IndicatorsOut: {
            /** Symbol */
            symbol: string;
            /** Dates */
            dates: string[];
            /** Columns */
            columns: string[];
            /** Data */
            data: (number | null)[][];
        };
        /** ScoreOut */
        ScoreOut: {
            /** Ticker */
            ticker: string;
            /** Last Price */
            last_price?: number | null;
            /** Roc 20D Pct */
            roc_20d_pct?: number | null;
            /** Rsi 14 */
            rsi_14?: number | null;
            /** Zscore 20 */
            zscore_20?: number | null;
            /** Trend */
            trend?: number | null;
            /** Momentum */
            momentum?: number | null;
            /** Macd */
            macd?: number | null;
            /** Mean Reversion */
            mean_reversion?: number | null;
            /** Score */
            score?: number | null;
            /** Signal */
            signal?: string | null;
        };
        /** EstimateSharesOut */
        EstimateSharesOut: {
            /** Ticker */
            ticker: string;
            /** Date */
            date: string;
            /** Amount Eur */
            amount_eur: number;
            /** Price Local */
            price_local: number;
            /** Listing Currency */
            listing_currency: string;
            /** Eur Per Local */
            eur_per_local: number;
            /** Shares */
            shares: number;
            /** Price Eur */
            price_eur: number;
        };
        /** SettingsOut */
        SettingsOut: {
            /** Adapter */
            adapter: string;
            /** Base Currency */
            base_currency: string;
            /** Av Quota */
            av_quota: {
                [key: string]: unknown;
            };
            /**
             * Av Api Key Set
             * @default false
             */
            av_api_key_set: boolean;
        };
        /**
         * SettingsUpdate
         * @description Body for ``PUT /api/settings``. Both fields optional.
         */
        SettingsUpdate: {
            /** Adapter */
            adapter?: string | null;
            /** Av Api Key */
            av_api_key?: string | null;
        };
        /**
         * CacheClearedOut
         * @description Response from ``POST /api/cache/clear``. Carries enough info for the
         *     SPA's top-bar Refresh button to show an "Updated at HH:MM" timestamp.
         */
        CacheClearedOut: {
            /** Adapter */
            adapter: string;
            /** At */
            at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    portfolio_app_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    portfolio_app_api_login_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    portfolio_app_api_logout_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    portfolio_app_api_get_portfolio: {
        parameters: {
            query?: {
                asset_class?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSnapshotOut"];
                };
            };
        };
    };
    portfolio_app_api_get_history: {
        parameters: {
            query?: {
                asset_class?: string;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValueHistoryOut"];
                };
            };
        };
    };
    portfolio_app_api_get_dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    portfolio_app_api_get_diversification: {
        parameters: {
            query?: {
                metric?: string;
                asset_class?: string;
                lookback?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiversificationOut"];
                };
            };
        };
    };
    portfolio_app_api_get_portfolio_signals: {
        parameters: {
            query?: {
                asset_class?: string;
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSignalsOut"];
                };
            };
        };
    };
    portfolio_app_api_get_watchlist_signals: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"];
                };
            };
        };
    };
    portfolio_app_api_list_transactions: {
        parameters: {
            query?: {
                ticker?: string | null;
                from?: string | null;
                to?: string | null;
                action?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"][];
                };
            };
        };
    };
    portfolio_app_api_create_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    portfolio_app_api_export_transactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    portfolio_app_api_delete_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tx_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    portfolio_app_api_update_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tx_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
        };
    };
    portfolio_app_api_create_holding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    portfolio_app_api_delete_holding: {
        parameters: {
            query?: {
                kind?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    portfolio_app_api_list_groups: {
        parameters: {
            query?: {
                asset_class?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupOut"][];
                };
            };
        };
    };
    portfolio_app_api_upsert_group: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    portfolio_app_api_delete_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_class: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    portfolio_app_api_update_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_class: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    portfolio_app_api_search_instruments: {
        parameters: {
            query: {
                q: string;
                type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentSearchHit"][];
                };
            };
        };
    };
    portfolio_app_api_get_instrument_quote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentQuoteOut"];
                };
            };
        };
    };
    portfolio_app_api_get_instrument_history: {
        parameters: {
            query?: {
                interval?: string;
                range?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryFrameOut"];
                };
            };
        };
    };
    portfolio_app_api_get_instrument_indicators: {
        parameters: {
            query?: {
                range?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorsOut"];
                };
            };
        };
    };
    portfolio_app_api_get_instrument_score: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreOut"];
                };
            };
        };
    };
    portfolio_app_api_estimate_shares: {
        parameters: {
            query: {
                amount_eur: number;
                /** @description Trade date */
                on: string;
                listing_currency?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateSharesOut"];
                };
            };
        };
    };
    portfolio_app_api_get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    portfolio_app_api_update_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    portfolio_app_api_clear_cache: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CacheClearedOut"];
                };
            };
        };
    };
}
